/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_duck_bahmod_Server */

#ifndef _Included_com_duck_bahmod_Server
#define _Included_com_duck_bahmod_Server
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_duck_bahmod_Server
 * Method:    rs_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_duck_bahmod_Server_rs_1start
  (JNIEnv *, jclass);

/*
 * Class:     com_duck_bahmod_Server
 * Method:    rs_add
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_duck_bahmod_Server_rs_1add
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_duck_bahmod_Server
 * Method:    rs_del
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_duck_bahmod_Server_rs_1del
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
